version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supermarket
      POSTGRES_DB_KEYCLOAK: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d/

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_DATABASE=keycloak
      - DB_USER=admin
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
    command:
      - start-dev

  backend:
    build:
      context: ./backend
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://username:password@localhost:5432/supermarket
    depends_on:
      - db
      - keycloak

  frontend-supermarket:
    build: ./supermarket-frontend
    container_name: supermarket-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend

  frontend-admin:
    build: ./admin-frontend
    container_name: admin-frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres-data:
